import dynamic from 'next/dynamic';
import type { ComponentType } from 'react';

/**
 * Registry of demo components generated by the pattern scaffolder.
 * The scaffolder appends an entry here when a new pattern is approved.
 * CodeExampleBlock reads from this registry in its default switch case.
 */
const agentReflectionLearningDemo = dynamic(() => import('./agent-reflection-learning-demo'), { ssr: false });
const workspaceNativeAgentsDemo = dynamic(() => import('./workspace-native-agents-demo'), { ssr: false });

export const scaffoldedDemos: Record<string, ComponentType> = {
  'agent-reflection-learning-demo': agentReflectionLearningDemo,
  'workspace-native-agents-demo': workspaceNativeAgentsDemo,
};
